nginx:
    build: ./nginx
    ports:
        - "80:80"
        - "443:443"
    links:
        - php
php:
    build: ./php
    links:
        - mysql
    volumes:
        - ./html:/var/www/html
        - ./ericseyden.com:/var/www/ericseyden.com
        - ./fatalexe.com:/var/www/fatalexe.com
        - ./seyden.net:/var/www/seyden.net
mysql:
    image: mysql:5
    environment:
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: secret
        MYSQL_RANDOM_ROOT_PASSWORD: "true"
